vlog -reportprogress 300 -work work {../include/core_pkg.sv}
vlog -reportprogress 300 -work work {../testbench/core_tb.sv}
vlog -reportprogress 300 -work work {../core.sv}
vlog -reportprogress 300 -work work {../Fetch.sv}
vlog -reportprogress 300 -work work {../Decode.sv}
vlog -reportprogress 300 -work work {../ALU.sv}
vlog -reportprogress 300 -work work {../DRAM.sv}
vlog -reportprogress 300 -work work {../DFlipFlop.sv}
vlog -reportprogress 300 -work work {../Register_File.sv}
vlog -reportprogress 300 -work work {../LSU.sv}